apiVersion: blockchain.5dlabs.io/v1alpha1
kind: SolanaNode
metadata:
  name: mainnet-rpc
  namespace: default
spec:
  nodeType: rpc
  enableVoting: false
  identitySecret: "solana-rpc-identity"
  knownValidators:
    - "7Np41oeYqPefeNQEHSv1UDhYrehxin3NStELsSKCT4K2"  # Certified Node
    - "HEL1USMZKAL2odpNBj2oCjffnFGaYwmbGmyewGv1e2TU"  # Helius
  entrypoints:
    - "entrypoint.mainnet-beta.solana.com:8001"
    - "entrypoint2.mainnet-beta.solana.com:8001"
  config:
    expectedGenesisHash: "5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d"
    limitLedgerSize: 200000000
    fullRpcApi: true
    enableAccountsDiskIndex: true
    skipStartupLedgerVerification: true
    rpcThreads: 128
    maximumFullSnapshotsToRetain: 2
    walRecoveryMode: "skip_any_corrupted_record"
  resources:
    cpuRequest: "16"
    memoryRequest: "64Gi"
    cpuLimit: "24"
    memoryLimit: "128Gi"